org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Force all modules to use compileSdk 36
android.compileSdk=36
android.targetSdk=36
android.buildToolsVersion=36.0.0

# Enable R8 full mode
android.enableR8.fullMode=true

# Disable Kotlin incremental compilation to fix cross-drive issues
kotlin.incremental=false