org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Force all modules to use compileSdk 35
android.compileSdk=35
android.targetSdk=35
android.buildToolsVersion=35.0.0

# Enable R8 full mode
android.enableR8.fullMode=true