// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvXo7_BOOHgs1psB3wweXgl8n1_esGPmQ',
    appId: '1:922341060283:web:5cd86a8f5cb672f73ac39e',
    messagingSenderId: '922341060283',
    projectId: 'sunday-school-8cde8',
    authDomain: 'sunday-school-8cde8.firebaseapp.com',
    storageBucket: 'sunday-school-8cde8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfRhdA1PQxXmQhN6xqxN71WRx1xwM2PSw',
    appId: '1:922341060283:android:1531e4c72e70e5303ac39e',
    messagingSenderId: '922341060283',
    projectId: 'sunday-school-8cde8',
    storageBucket: 'sunday-school-8cde8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvmyOlwJq5GF7m9pEz3TsSoGSRIwX5FjA',
    appId: '1:922341060283:ios:a5f3fa7a55e568873ac39e',
    messagingSenderId: '922341060283',
    projectId: 'sunday-school-8cde8',
    storageBucket: 'sunday-school-8cde8.firebasestorage.app',
    iosBundleId: 'com.example.sundayschoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvmyOlwJq5GF7m9pEz3TsSoGSRIwX5FjA',
    appId: '1:922341060283:ios:a5f3fa7a55e568873ac39e',
    messagingSenderId: '922341060283',
    projectId: 'sunday-school-8cde8',
    storageBucket: 'sunday-school-8cde8.firebasestorage.app',
    iosBundleId: 'com.example.sundayschoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvXo7_BOOHgs1psB3wweXgl8n1_esGPmQ',
    appId: '1:922341060283:web:3c43605342efc5583ac39e',
    messagingSenderId: '922341060283',
    projectId: 'sunday-school-8cde8',
    authDomain: 'sunday-school-8cde8.firebaseapp.com',
    storageBucket: 'sunday-school-8cde8.firebasestorage.app',
  );

}